CREATE DATABASE SGPI_BD
USE [SGPI_BD]
GO
/****** Object:  Database [SGPI_BD]    Script Date: 13/10/2022 11:44:28 a. m. ******/
CREATE DATABASE [SGPI_BD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SGPI_BD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SGPI_BD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SGPI_BD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SGPI_BD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SGPI_BD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SGPI_BD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SGPI_BD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SGPI_BD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SGPI_BD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SGPI_BD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SGPI_BD] SET ARITHABORT OFF 
GO
ALTER DATABASE [SGPI_BD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SGPI_BD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SGPI_BD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SGPI_BD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SGPI_BD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SGPI_BD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SGPI_BD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SGPI_BD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SGPI_BD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SGPI_BD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SGPI_BD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SGPI_BD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SGPI_BD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SGPI_BD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SGPI_BD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SGPI_BD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SGPI_BD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SGPI_BD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SGPI_BD] SET  MULTI_USER 
GO
ALTER DATABASE [SGPI_BD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SGPI_BD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SGPI_BD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SGPI_BD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SGPI_BD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SGPI_BD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SGPI_BD] SET QUERY_STORE = OFF
GO
USE [SGPI_BD]
GO
/****** Object:  Table [dbo].[Documento]    Script Date: 13/10/2022 11:44:28 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Documento](
	[IdDoc] [int] IDENTITY(1,1) NOT NULL,
	[TipoDocumento] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdDoc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Entrevista]    Script Date: 13/10/2022 11:44:29 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Entrevista](
	[IdEntrevista] [int] IDENTITY(1,1) NOT NULL,
	[IdUsuario] [int] NOT NULL,
	[IdEstudiante] [int] NOT NULL,
	[Fecha] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdEntrevista] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estudiante]    Script Date: 13/10/2022 11:44:29 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estudiante](
	[IdEstudiante] [int] NOT NULL,
	[Archivo] [varchar](50) NOT NULL,
	[IdPago] [int] NOT NULL,
	[IdUsuario] [int] NOT NULL,
	[Egresado] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdEstudiante] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Genero]    Script Date: 13/10/2022 11:44:29 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Genero](
	[IdGenero] [int] IDENTITY(1,1) NOT NULL,
	[Genero] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdGenero] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Homologacion]    Script Date: 13/10/2022 11:44:29 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Homologacion](
	[IdHomologacion] [int] IDENTITY(1,1) NOT NULL,
	[IdEstudiante] [int] NOT NULL,
	[PeriodoAcademico] [varchar](50) NOT NULL,
	[Nota] [float] NOT NULL,
	[IdPrograma] [int] NOT NULL,
	[IdModulo] [int] NOT NULL,
	[CodigoHomologacion] [varchar](50) NOT NULL,
	[NomAsigHomologacion] [varchar](50) NOT NULL,
	[CreditosHomologacion] [int] NOT NULL,
	[IdTipoHomolo] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdHomologacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Modulo]    Script Date: 13/10/2022 11:44:29 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Modulo](
	[IdModulo] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](500) NOT NULL,
	[Codigo] [varchar](50) NOT NULL,
	[IdPrograma] [int] NOT NULL,
	[Nivel] [int] NOT NULL,
	[Creditos] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdModulo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pago]    Script Date: 13/10/2022 11:44:29 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pago](
	[IdPago] [int] IDENTITY(1,1) NOT NULL,
	[Fecha] [date] NOT NULL,
	[Valor] [int] NOT NULL,
	[Estado] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdPago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Programa]    Script Date: 13/10/2022 11:44:29 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Programa](
	[IdPrograma] [int] IDENTITY(1,1) NOT NULL,
	[Programa] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdPrograma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Programacion]    Script Date: 13/10/2022 11:44:29 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Programacion](
	[IdProgramacion] [int] IDENTITY(1,1) NOT NULL,
	[PeriodoAcademico] [varchar](50) NOT NULL,
	[IdPrograma] [int] NOT NULL,
	[FechaProgramacion] [datetime] NOT NULL,
	[Salon] [varchar](50) NOT NULL,
	[IdModulo] [int] NOT NULL,
	[IdUsuario] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdProgramacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rol]    Script Date: 13/10/2022 11:44:29 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rol](
	[IdRol] [int] IDENTITY(1,1) NOT NULL,
	[TipoRol] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdRol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipoHomologacion]    Script Date: 13/10/2022 11:44:29 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipoHomologacion](
	[IdTipoHomologacion] [int] IDENTITY(1,1) NOT NULL,
	[TipoHomologacion] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdTipoHomologacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 13/10/2022 11:44:29 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NOT NULL,
	[Documento] [varchar](50) NOT NULL,
	[IdDoc] [int] NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Telefono] [int] NOT NULL,
	[IdPrograma] [int] NOT NULL,
	[IdRol] [int] NOT NULL,
	[IdGenero] [int] NOT NULL,
	[Password] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Entrevista]  WITH CHECK ADD  CONSTRAINT [FK_Entrevista_Usuario] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuario] ([IdUsuario])
GO
ALTER TABLE [dbo].[Entrevista] CHECK CONSTRAINT [FK_Entrevista_Usuario]
GO
ALTER TABLE [dbo].[Entrevista]  WITH CHECK ADD  CONSTRAINT [FK_IdEstudiante] FOREIGN KEY([IdEstudiante])
REFERENCES [dbo].[Estudiante] ([IdEstudiante])
GO
ALTER TABLE [dbo].[Entrevista] CHECK CONSTRAINT [FK_IdEstudiante]
GO
ALTER TABLE [dbo].[Estudiante]  WITH CHECK ADD  CONSTRAINT [FK_IdEstudianteUsuario] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuario] ([IdUsuario])
GO
ALTER TABLE [dbo].[Estudiante] CHECK CONSTRAINT [FK_IdEstudianteUsuario]
GO
ALTER TABLE [dbo].[Estudiante]  WITH CHECK ADD  CONSTRAINT [FK_IdPago] FOREIGN KEY([IdPago])
REFERENCES [dbo].[Pago] ([IdPago])
GO
ALTER TABLE [dbo].[Estudiante] CHECK CONSTRAINT [FK_IdPago]
GO
ALTER TABLE [dbo].[Homologacion]  WITH CHECK ADD  CONSTRAINT [FK_Homologacion_Estudiante] FOREIGN KEY([IdEstudiante])
REFERENCES [dbo].[Estudiante] ([IdEstudiante])
GO
ALTER TABLE [dbo].[Homologacion] CHECK CONSTRAINT [FK_Homologacion_Estudiante]
GO
ALTER TABLE [dbo].[Homologacion]  WITH CHECK ADD  CONSTRAINT [FK_Homologacion_Modulo] FOREIGN KEY([IdModulo])
REFERENCES [dbo].[Modulo] ([IdModulo])
GO
ALTER TABLE [dbo].[Homologacion] CHECK CONSTRAINT [FK_Homologacion_Modulo]
GO
ALTER TABLE [dbo].[Homologacion]  WITH CHECK ADD  CONSTRAINT [FK_Homologacion_Programa] FOREIGN KEY([IdPrograma])
REFERENCES [dbo].[Programa] ([IdPrograma])
GO
ALTER TABLE [dbo].[Homologacion] CHECK CONSTRAINT [FK_Homologacion_Programa]
GO
ALTER TABLE [dbo].[Homologacion]  WITH CHECK ADD  CONSTRAINT [FK_Homologacion_TipoHomologacion] FOREIGN KEY([IdHomologacion])
REFERENCES [dbo].[TipoHomologacion] ([IdTipoHomologacion])
GO
ALTER TABLE [dbo].[Homologacion] CHECK CONSTRAINT [FK_Homologacion_TipoHomologacion]
GO
ALTER TABLE [dbo].[Modulo]  WITH CHECK ADD  CONSTRAINT [FK_Modulo_Programa] FOREIGN KEY([IdPrograma])
REFERENCES [dbo].[Programa] ([IdPrograma])
GO
ALTER TABLE [dbo].[Modulo] CHECK CONSTRAINT [FK_Modulo_Programa]
GO
ALTER TABLE [dbo].[Programacion]  WITH CHECK ADD  CONSTRAINT [FK_IdAsignaturaProgramacion] FOREIGN KEY([IdModulo])
REFERENCES [dbo].[Modulo] ([IdModulo])
GO
ALTER TABLE [dbo].[Programacion] CHECK CONSTRAINT [FK_IdAsignaturaProgramacion]
GO
ALTER TABLE [dbo].[Programacion]  WITH CHECK ADD  CONSTRAINT [FK_IdProgramaProgramacion] FOREIGN KEY([IdPrograma])
REFERENCES [dbo].[Programa] ([IdPrograma])
GO
ALTER TABLE [dbo].[Programacion] CHECK CONSTRAINT [FK_IdProgramaProgramacion]
GO
ALTER TABLE [dbo].[Programacion]  WITH CHECK ADD  CONSTRAINT [FK_IdUsuarioProgramacion] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuario] ([IdUsuario])
GO
ALTER TABLE [dbo].[Programacion] CHECK CONSTRAINT [FK_IdUsuarioProgramacion]
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_Documento] FOREIGN KEY([IdDoc])
REFERENCES [dbo].[Documento] ([IdDoc])
GO
ALTER TABLE [dbo].[Usuario] CHECK CONSTRAINT [FK_Usuario_Documento]
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_Genero] FOREIGN KEY([IdGenero])
REFERENCES [dbo].[Genero] ([IdGenero])
GO
ALTER TABLE [dbo].[Usuario] CHECK CONSTRAINT [FK_Usuario_Genero]
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_Programa] FOREIGN KEY([IdPrograma])
REFERENCES [dbo].[Programa] ([IdPrograma])
GO
ALTER TABLE [dbo].[Usuario] CHECK CONSTRAINT [FK_Usuario_Programa]
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_Rol] FOREIGN KEY([IdRol])
REFERENCES [dbo].[Rol] ([IdRol])
GO
ALTER TABLE [dbo].[Usuario] CHECK CONSTRAINT [FK_Usuario_Rol]
GO
USE [SGPI_BD]
GO
ALTER DATABASE [SGPI_BD] SET  READ_WRITE 
GO